#! /usr/bin/env bash

# Update the system
sudo apt update && sudo apt upgrade -y

# Install Babashka if it doesn't exit
which bb > /dev/null
if [ $? -eq 1 ]
then
	echo "Installing Babashka"
	curl -sL -o /tmp/bb-install https://raw.githubusercontent.com/babashka/babashka/master/install
	chmod 700 /tmp/bb-install
	sudo /tmp/bb-install
	rm /tmp/bb-install
else
	echo "Babashka is already installed...skipping"
fi

# Install rlwrap to use for command line history in Babashka
which rlwrap > /dev/null
if [ $? -eq 1 ]
then
	echo "Installing rlwrap"
	sudo apt install rlwrap
else
	echo "rlwrap already installed...skipping"
fi

# TODO turn this into a script and require HOSTNAME as arg 1
sudo hostnamectl set-hostname HOSTNAME
sudo apt install -y snap
sudo snap install bw

# Set up local secret storage
export SECRETS_DIR=~/.local/secrets.d
mkdir -p $SECRETS_DIR
touch $SECRETS_DIR/bitwarden
chmod 700 $SECRETS_DIR $SECRETS_DIR/bitwarden
echo "export BW_CLIENTID=" | cat > $SECRETS_DIR/bitwarden
echo "export BW_CLIENTSECRET=" | cat >> $SECRETS_DIR/bitwarden

# Generate new github key pair for this machine
ssh-keygen -t ed25519 -C "don@donthorp.net" -f ~/.ssh/`hostname`-github -N ""
mkdir -p ~/.ssh/config.d
chmod 700 ~/.ssh/config.d

cat > ~/.ssh/config.d/github.com <<EOF
Host github.com
  User git
  Port 22
  Hostname github.com
  IdentityFile ~/.ssh/`hostname`-github.pub
  TCPKeepAlive yes
  IdentitiesOnly yes
  AddKeysToAgent yes
EOF 

echo Visit https://github.com/settings/keys and add this machines public key
cat ~/.ssh/`hostname`-github.pub

sudo snap install --stable --classic chezmoi
